### ISSUE TITLE
Annotate the legend for sc UMAP plots where label = plate

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/luad-cell-painting#1]
![image](https://user-images.githubusercontent.com/1210428/139479056-5336b1c1-eaf6-4f20-8f61-a96294dc0029.png)

From https://broadinstitute.github.io/luad-cell-painting/variants/BRAF_p.W450L/

It's not obvious what the numbers 52662 etc refer to (they are plates)

**Comment by johnarevalo** [comment]
@jccaicedo, you can push the updated images directly in the [gh-pages](/broadinstitute/luad-cell-painting/tree/gh-pages) branch, in the [assets/images/single-cell](/broadinstitute/luad-cell-painting/tree/gh-pages/assets/images/single-cell) folder. The site should be updated automatically.

You also can send me the location of the new images and I update them.

**Comment by jccaicedo** [comment]
I don't think the images need to be re-generated again. What we need to do is to add more documentation to the webpage (titles, legends and comments). This applies not only to these plots, but also to Venn diagrams, matrices, dot / box plots, and so on. We can draft such descriptions in a shared document and then add them to the website.

What do you think?

**Comment by jccaicedo** [comment]
The website makes sense only to those who have read the full paper, so it would be great to have the site kind of self-contained with sufficient explanations. I can help with these writings if you agree.

**Comment by johnarevalo** [comment]
Sure, that's a great idea. I shared a Google doc with some initial text.

**Comment by johnarevalo** [comment]
The website now includes the descriptions defined in the GDoc. Closing this issue.
