### ISSUE TITLE
No Cells to Profile

### ISSUE THREAD

**Issue by roshankern** [broadinstitute/luad-cell-painting#6]
I have managed to follow profiling steps 1-3 (requirements installation, data download, data preparation) without any apparent issues.
However, when I run the command shown in step 4 to extract features, I encounter 2 issues:

1. First, I get `KeyError: label_smoothing`. This was easily resolved by adding `"label_smoothing": 0.0` under `train: model: params`
2. After resolving issue 1, the profile command runs but says `No cells to profile` for each image (ex: `No cells to profile: .//outputs/efn_pretrained/features//52649/p10/3.npz`)

I have tried running step 4 with both the latest commit of DeepProfiler as well as commit [`c91b9d8`](https://github.com/cytomining/DeepProfiler/tree/c91b9d821a37d90583d19d209be2e53fe3f08d8d) which is mentioned in this repository.

Why is DeepProfiler not able to detect any cells to profile?

**Comment by johnarevalo** [comment]
Hi @roshankern , We forgot to document the cell location extraction step, sorry about it. You should be able to generate the location files by running the [extract_locations.py](https://github.com/broadinstitute/luad-cell-painting/blob/main/utils/extract_locations.py) script. Please try the following:

 1) download the SQLite files using the `download_all.sh` script
 2) run the `extract_locations.py` script
 3) repeat the feature extraction part.

I hope this helps.

**Comment by roshankern** [comment]
Works perfectly, thank you!
